# Uncomment the next line to define a global platform for your project

source 'https://gitee.com/hanyfeng89/OSC_HFCommon_Spec.git'
source 'https://gitee.com/hanyfeng89/OSC_HFNetwork_Spec.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
inhibit_all_warnings!

target 'MyIOSDevelopTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XTJMall
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'YYModel'
  pod 'IQKeyboardManager'
  # pod 'KVOController'
  pod 'JTCalendar'
  pod 'FFRouter'
  pod "RTRootNavigationController"
  pod 'CocoaLumberjack'
  pod 'ReactiveObjC'
  # pod 'KSCrash'

  #开发模式下用，生产模式下要去掉
  # pod 'MLeaksFinder'
  # pod 'FBMemoryProfiler'
  # pod 'NSLogger'
  
  pod 'HFNetwork'
end
